#!/bin/bash

# Fixed rebuild.bash script that combines reset and content in a single JSON array

echo "[
  {\"\": \"reset\"},
  {\"Javascript\": \"// Generated by rebuild.bash\\nconsole.log('Hello from rebuild');\"},
  {\"Python\": \"# Generated by rebuild.bash\\nprint('Hello from rebuild')\"},
  {\"Info\": \"<div>Rebuild completed successfully at $(date)</div>\"}
]"

exit 0
